### PR TITLE
[Feature: ADF-48] Move export table button to bottom

### PR DESCRIPTION
**Pull request by habemuscode**
**Issue**

https://oat-sa.atlassian.net/browse/ADF-48

**Description**

As a back-office user, I want to have easy access to contextual actions related to a delivery execution result so that I can use those actions right from the delivery execution result page

Because some of the actions related to the delivery execution result are only available on the delivery result list, they become unavailable when navigating to this page using search. To make them available again, we should include them on the delivery execution result page.

The export table is associated with the selected delivery and not the delivery execution result. This can be made clearer by moving it below the tree

**Acceptance Criteria**

- When viewing a delivery execution result, the print, download, delete actions must be available within the detailed result page

- While on the Results extension, the export table button should be situated below the tree, next to export to CSV

** Environment **
Deployed to the playground, the link is in the ticket

### CODE REVIEW

**Comment by 404passionFruit** [comment]
Updated css files because prev version was committed to this PR

**Review by habemuscode — COMMENTED** [review]
Its my PR bit contains @404passionFruit work that I validate. This is not a self-approval :D

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Comment by AntonNeviarouski** [comment]
QA validated on http://test-sveta-a-a-a.playground.kitchen.it.taocloud.org:44691/

**Pull request merged**
