### PR TITLE
[Fix: CON 573] - Empty button results tab

### PR DESCRIPTION
**Pull request by habemuscode**
**Issue**

https://oat-sa.atlassian.net/browse/CON-573

**Description**

In the results tab in Authoring, the button related to results doesn't have an icon or text

image

### CODE REVIEW

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by bziondik — CHANGES_REQUESTED** [review]
Checked locally.
Expected result: The UI has no empty buttons. - failed
image

**Comment by habemuscode** [comment]
Now you can check here: http://test-juan.playground.kitchen.it.taocloud.org:49241/tao/Main/index?structure=results&ext=taoOutcomeUi&section=manage_results&uri=http%3A%2F%2Fwww.tao.lu%2FOntologies%2FTAODelivery.rdf%23AssembledDelivery

**Review by bziondik — APPROVED** [review]
image
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
